### ISSUE TITLE
name 'self' is not defined,  CTY.PLIST could not be loaded, errors

### ISSUE THREAD

**Issue by coolest42u** [aa2il/pySDR#1]
Hi , i got those errors while executing.  

my system:
Ubuntu 22.04
RTL-SDR
Python3.10

**Comment by aa2il** [comment]
You are probably missing the cty.bin file.  It has been added to the "data" directory.  Please re-clone the data directory and try again.

**Comment by coolest42u** [comment]
ok it works thank you :D

**Comment by coolest42u** [comment]
Thank you for your help,
 by the way 
I have upconverter (hamitup) is it possible to add frequency shift ?

**Comment by aa2il** [comment]
Yes, it should be possible.  It might already be in the code already but I don't have an upconverter to try it out.  Try using the
 -foffset parameter to see if this does what you want.  If not, such a capability is easy to add.

BTW, thank you for your feedback and alerting me to the original problem.

**Comment by coolest42u** [comment]
Your welcome,

i got tihs error when i use ./pySDR -foffset 125000 

*** ERROR in setupSDR: requested RF offset outside tuner bandwidth
Offset = 125000.0  KHz            Max = Half Bandwidth = 1024.0  KHz

and i think i have to disable direct sampling too. its automaticly change sampling to 1 or 2 it must be 0 or disabled

**Comment by aa2il** [comment]
Ok - I'll take a closer look at how to include an offset.  
If you use the -rtl switch, that should disable the direct sampling.  You can get a list of all of the command line parameters using the --help switch.
73 - Joe

**Comment by aa2il** [comment]
Hello again - I've added a flag "-hamitup" to the command line arguments that should take care of the offset for your up-converter.  It also disables the direct sampling.  I do not have a way of testing it so please let me know if this works for you.   You will need three updated files from the pySDR directory - params.py, gui.py and receiver.py.  Thanks.

**Comment by coolest42u** [comment]
Hello, yesss it works like a charm :D without any problem.Thank you again for your help and quick response.

**Comment by coolest42u** [comment]
Solved

**Comment by coolest42u** [comment]
![screen](https://github.com/user-attachments/assets/e736c4c9-dbf5-4e8a-9ae3-0befb3cd9d0f)

My screenshot :D

**Comment by coolest42u** [comment]
![screen](https://github.com/user-attachments/assets/e736c4c9-dbf5-4e8a-9ae3-0befb3cd9d0f)

My screenshot :D

**Comment by aa2il** [comment]
Excellent - good luck and thanks again for the feedback.  BTW, where are you and do you have a callsign?
73 - Joe

**Comment by coolest42u** [comment]
> Excellent - good luck and thanks again for the feedback. BTW, where are you and do you have a callsign? 73 - Joe

I'm from Ankara, Turkey, unfortunately i don't have any callsing yet. if i get one, i will share with you. thanks again. izzet
