### ISSUE TITLE
INSTALLATION ERROR

### ISSUE THREAD

**Issue by COVAILAB1** [aa2il/pySDR#2]
ster/pySDR-master/pySDR.py
Traceback (most recent call last):
  File "c:\Users\tamil\Downloads\pySDR-master\pySDR-master\pySDR.py", line 65, in <module>
    import sig_proc as dsp
ModuleNotFoundError: No module named 'sig_proc'

**Comment by satmonkey** [comment]
What is the solution? I am having the same issue.

**Comment by aa2il** [comment]
sig_proc is in the libs directory.  Make sure you have set the PYTHONPATH so that the interprettor can find it.  See the instructions in README.

**Comment by satmonkey** [comment]
thank you!
I went through the README again, and it seems to be on the right track now.
I was confused by the ~/Python, and had to modify the path to the correct one.

**Comment by aa2il** [comment]
Very good.  The ~/ just refers to your home directory but you should be able to move things to whereever it is convenient.  
73 - Joe
